### ISSUE TITLE
Update to raylib 3.7

### ISSUE THREAD

**Issue by makew0rld** [chunqian/go-raylib#11] opened 2021-04-26 16:46 UTC
raylib 3.7 was just [released](https://github.com/raysan5/raylib/releases/tag/3.7.0). No rush on the update, just wanted to make this issue just in case.

Thanks for all your work maintaining this library! :smile:

**Comment by chunqian** [comment] 2021-04-26 22:29
I'll do some work in the other branches first

**Comment by ghost** [comment] 2021-05-13 16:30
Are there plans to someday port over raygui with 3.7?

**Comment by chunqian** [comment] 2021-05-14 00:10
Raylib's ecology will support, raygui rres...
There are currently issues that need to be resolved.
The main thing is cgo after build, link use `.o`,  redefine error need to fix.
As soon as I can.

**Comment by chunqian** [comment] 2021-05-14 00:13
Raygui has been ported before...
But use of cgo build c source, i removed it...
The problem is what I said above.

**Comment by chunqian** [comment] 2021-05-14 03:17
@conifer-dev 
now bindings ricons.h raygui.h in raylib 3.5
raylib 3.7 bindings coming soon

**Comment by chunqian** [comment] 2021-05-19 09:39
Raylib 3.7 are still have many bugs.
go-raylib branch 3.7 complete the binding.

**Comment by chunqian** [comment] 2021-05-26 13:57
main branch will keep 3.5 binding.
when almost bugs fixed, then update to the lastest version binding.

**Comment by chunqian** [comment] 2021-11-08 01:21
raylib 4.0 has been released
go-raylib will also be updated to 4.0 in the near future
Close this issue for now.

**Closed as completed by chunqian** 2021-11-08 01:21 UTC
